module.exports = [
    { system: 'acsr', releaseName: 'Release 1', applicationGroup: 'BP' },
    { system: 'adwTarget', releaseName: 'Production', applicationGroup: 'AI' },
    { system: 'agency economics', releaseName: 'Version 1', applicationGroup: 'BW' },
    { system: 'alliance', releaseName: 'Release 1', applicationGroup: 'BE' },
    { system: 'allstate financial', releaseName: 'Production', applicationGroup: 'AJ' },
    { system: 'allstate representative repository', releaseName: 'Release 1', applicationGroup: 'BJ' },
    { system: 'ams', releaseName: 'Production', applicationGroup: 'CA' },
    { system: 'arms', releaseName: 'Production', applicationGroup: 'CF' },
    { system: 'billing', releaseName: 'Production', applicationGroup: 'AR' },
    { system: 'cfr product availability', releaseName: 'Release 1', applicationGroup: 'BI' },
    { system: 'claims', releaseName: 'Release 1', applicationGroup: 'AT' },
    { system: 'csg', releaseName: 'Version 1', applicationGroup: 'BL' },
    { system: 'customer and enterprise services', releaseName: 'Release 1', applicationGroup: 'BC' },
    { system: 'dmea', releaseName: 'Production', applicationGroup: 'AY' },
    { system: 'dotMAX', releaseName: 'Release 1', applicationGroup: 'BM' },
    { system: 'drivewise', releaseName: 'Release 1', applicationGroup: 'CC' },
    { system: 'ecs', releaseName: 'Production', applicationGroup: 'BK' },
    { system: 'encompass', releaseName: 'Production', applicationGroup: 'BU' },
    { system: 'enterprise support service', releaseName: 'Release 1', applicationGroup: 'CE' },
    { system: 'hrm', releaseName: 'Production', applicationGroup: 'AC' },
    { system: 'iProcess infrastructure', releaseName: 'Production', applicationGroup: 'BG' },
    { system: 'ics', releaseName: 'Production', applicationGroup: 'AX' },
    { system: 'idm', releaseName: 'Release 1', applicationGroup: 'BQ' },
    { system: 'ins', releaseName: 'Production', applicationGroup: 'CG' },
    { system: 'ivantage', releaseName: 'Production', applicationGroup: 'CB' },
    { system: 'lexisNexis', releaseName: 'Release 1', applicationGroup: 'BF' },
    { system: 'marketing', releaseName: 'Release 1', applicationGroup: 'BA' },
    { system: 'misc', releaseName: 'Production', applicationGroup: 'BS' },
    { system: 'ms dynamic', releaseName: 'Production', applicationGroup: 'CH' },
    { system: 'myAccount', releaseName: 'Production', applicationGroup: 'BD' },
    { system: 'nextGen', releaseName: 'Release 1', applicationGroup: 'AQ' },
    { system: 'pim', releaseName: 'PROD', applicationGroup: 'BY' },
    { system: 'property services', releaseName: 'Production', applicationGroup: 'CJ' },
    { system: 'quote insurance proposal', releaseName: 'Release 1', applicationGroup: 'CI' },
    { system: 'sales and service integration bus', releaseName: 'Release 1', applicationGroup: 'BV' },
    { system: 'sap', releaseName: 'Production', applicationGroup: 'AP' },
    { system: 'siebel', releaseName: 'Production', applicationGroup: 'BR' },
    { system: 'smce', releaseName: 'Production', applicationGroup: 'BH' },
    { system: 'sod', releaseName: 'Production', applicationGroup: 'CD' },
    { system: 'vended applications', releaseName: 'Production', applicationGroup: 'BX' }
];


